export const governoratesWithCities: Record<string, string[]> = {
  Tunis: [
    "Bab Bhar",
    "Bab Souika",
    "Carthage",
    "Cité El Khadra",
    "Djebel Jelloud",
    "El Haraïria",
    "El Kabaria",
    "El Menzah",
    "El Omrane",
    "El Omrane Supérieur",
    "El Ouardia",
    "Ettahrir",
    "Ezzouhour",
    "La Goulette",
    "La Marsa",
    "Le Bardo",
    "Le Kram",
    "Medina",
    "Sidi El Béchir",
    "Sidi Hassine",
    "Sijoumi",
  ],

  Ariana: [
    "Ariana Ville",
    "Ettadhamen",
    "La Soukra",
    "Kalaat El Andalous",
    "Mnihla",
    "Gammarth",
    "Berges du Lac",
  ],

  Beja: [
    "Beja Nord",
    "Beja Sud",
    "Testour",
    "Téboursouk",
    "Zahret Medien",
    "Zelba",
    "Thibar",
    "Goubellat",
    "Majaz El Bab",
  ],

  "Ben_Arous": [
    "Ben Arous",
    "Hammam Lif",
    "Hammam Chott",
    "Mohamedia",
    "Fouchana",
    "Mornag",
    "Boumhel",
    "Ezzahra",
    "Radès",
  ],

  Bizerte: [
    "Bizerte Nord",
    "Bizerte Sud",
    "Ras Jebel",
    "Menzel Bourguiba",
    "Ghar El Melh",
    "Mateur",
    "Sejnane",
    "Joumine",
    "Tinja",
    "Menzel Jemil",
  ],

  Gabes: [
    "Gabes Ville",
    "Gabes Ouest",
    "Gabes Sud",
    "Gabes Médina",
    "Ghannouch",
    "Matmata",
    "Matmata Nouvelle",
  ],

  Gafsa: [
    "Gafsa Ville",
    "Redeyef",
    "Metlaoui",
    "Gafsa Nord",
    "Gafsa Sud",
    "Moularès",
    "Mdhilla",
    "El Ksar",
    "El Guettar",
  ],

  Jendouba: [
    "Jendouba Nord",
    "Jendouba Sud",
    "Aïn Draham",
    "Fernana",
    "Ghardimaou",
    "Oued Meliz",
    "Tabarka",
    "Balta Bou Aouane",
  ],

  Kairouan: [
    "Kairouan Nord",
    "Kairouan Sud",
    "Sbikha",
    "Nasrallah",
    "Chebika",
    "Haffouz",
  ],

  Kasserine: [
    "Kasserine Nord",
    "Kasserine Sud",
    "Sbeitla",
    "Sbiba",
    "Feriana",
    "El Ayoun",
    "Thala",
  ],

  Kebili: [
    "Kebili Nord",
    "Kebili Sud",
    "Douz Nord",
    "Douz Sud",
  ],

  "Le_Kef": [
    "Kef Est",
    "Kef Ouest",
    "Dahmani",
    "Jerissa",
    "Kalaat Khesba",
    "Nebeur",
    "Sers",
    "Tajerouine",
  ],

  Mahdia: [
    "Mahdia",
    "Ksour Essef",
    "Chebba",
    "Bou Merzoug",
    "Melloulech",
    "El Jem",
    "Ouled Chamekh",
  ],

  "La_Manouba": [
    "Douar Hicher",
    "Oued Ellil",
    "Mornaguia",
    "Borj El Amri",
    "La Manouba",
    "Jedaida",
  ],

  Medenine: [
    "Medenine Ville",
    "Zarzis",
    "Ben Guerdane",
    "Djerba Ajim",
    "Djerba Midoun",
    "Djerba Houmet Essouk",
  ],

  Monastir: [
    "Monastir",
    "Moknine",
    "Ksar Hellal",
    "Sahline",
    "Bembla",
    "Jammel",
    "Beni Hassen",
  ],

  Nabeul: [
    "Nabeul",
    "Hammamet",
    "Kelibia",
    "Korba",
    "Grombalia",
    "Menzel Temime",
    "Soliman",
    "Dar Chaabane El Fehri",
    "Takelsa",
  ],

  Sfax: [
    "Sfax Médina",
    "Sfax Sud",
    "Sfax Ouest",
    "Sakiet Ezzit",
    "Bir Ali Ben Khelifa",
    "Gremda",
    "Agareb",
    "Jebeniana",
    "Hencha",
  ],

  "Sidi_Bouzid": [
    "Sidi Bouzid Ville",
    "Regueb",
    "Meknassy",
    "Sidi Ali Ben Aoun",
    "Menzel Bouzaiane",
    "Jilma",
    "Bir El Hafey",
  ],

  Siliana: [
    "Siliana Nord",
    "Siliana Sud",
    "Kesra",
    "Makthar",
    "El Aroussa",
    "Rouhia",
  ],

  Sousse: [
    "Sousse",
    "Hammam Sousse",
    "Kalaa Sghira",
    "Enfidha",
    "Hergla",
    "Kondar",
    "Sayada Lamta Bouhjar",
    "Akouda",
    "Kalâa Kebira",
    "M'saken",
  ],

  Tataouine: [
    "Tataouine Nord",
    "Tataouine Sud",
    "Remada",
    "Bir Lahmar",
    "Dehiba",
    "Smar",
  ],

  Tozeur: [
    "Tozeur",
    "Degueche",
    "Hazoua",
    "Nefta",
  ],

  Zaghouan: [
    "Zaghouan",
    "El Fahs",
    "Nadhour",
    "Zriba",
  ],
};
